
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Esses valores serão substituídos pelo script env.sh em tempo de execução
const SUPABASE_URL = "SUPABASE_URL_PLACEHOLDER";
const SUPABASE_PUBLISHABLE_KEY = "SUPABASE_ANON_KEY_PLACEHOLDER";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
