
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Define values for development and production environments
let supabaseUrl: string;
let supabaseKey: string;

// Check if the values are placeholders
if (typeof SUPABASE_URL_PLACEHOLDER === 'undefined' || SUPABASE_URL_PLACEHOLDER === "SUPABASE_URL_PLACEHOLDER") {
  // Use hardcoded values for development
  supabaseUrl = "https://cfhjwvibgiierhvaafrd.supabase.co";
  supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmaGp3dmliZ2lpZXJodmFhZnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODI1NjcsImV4cCI6MjA1OTM1ODU2N30.3GvW0fV610dUXnQgF08XhT5EPKIwHoyfAQRgCSGN4EM";
} else {
  // Use placeholder values for production (will be replaced by env.sh)
  supabaseUrl = SUPABASE_URL_PLACEHOLDER;
  supabaseKey = SUPABASE_ANON_KEY_PLACEHOLDER;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);
